# Generated by Django 5.2 on 2025-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('machine', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sf', models.CharField(max_length=50)),
                ('mp', models.CharField(max_length=50)),
                ('equipe', models.CharField(max_length=50)),
                ('motif', models.CharField(max_length=100)),
                ('controle_bobines', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=50)),
                ('pression_entree', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pression_courroie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aspect', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=50)),
                ('verification_blo', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=50)),
                ('fil1_nom', models.CharField(max_length=50)),
                ('fil1_L1_theorique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fil1_L1_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fil2_nom', models.CharField(max_length=50)),
                ('fil2_L2_theorique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fil2_L2_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_num', models.CharField(max_length=50)),
                ('miniapp1', models.CharField(max_length=50)),
                ('cmp1_hc_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_hc_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_hc_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_hr_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_hr_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_hr_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_tr_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp1_tr_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_num', models.CharField(max_length=50)),
                ('miniapp2', models.CharField(max_length=50)),
                ('cmp2_hc_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_hc_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_hc_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_hr_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_hr_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_hr_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_tr_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmp2_tr_mesuree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validation_status', models.CharField(choices=[('Valide', 'Valide'), ('Non Valide', 'Non Valide'), ('En attente', 'En attente')], default='En attente', max_length=20)),
            ],
        ),
    ]
