# Generated by Django 5.2 on 2025-06-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='fil2_L2_theorique',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
